#!/usr/bin/env python3
"""Generate internal/xidb/titles_gen.go from the xiserver title enum.

char_stats.title holds a numeric title id. The only authoritative id-to-name
mapping is scripts/enum/title.lua in the server repo, which is why this is
generated rather than hand-maintained: 1100 entries that change whenever the
server adds content.

    ./tools/gen_titles.py ../xiserver/scripts/enum/title.lua
"""

import argparse
import os
import re
import sys

ENTRY = re.compile(r'^\s*([A-Z0-9_]+)\s*=\s*(\d+)\s*,')

# Words the title table spells in caps that should not be title-cased blindly.
ACRONYMS = {'Nm': 'NM', 'Bcnm': 'BCNM', 'Ksnm': 'KSNM', 'Enm': 'ENM',
            'Hnm': 'HNM', 'Wsnm': 'WSNM', 'Vs': 'vs', 'Of': 'of',
            'The': 'the', 'And': 'and', 'In': 'in', 'To': 'to', 'A': 'a'}


def humanize(ident):
    words = [w.capitalize() for w in ident.split('_') if w]
    out = []
    for i, w in enumerate(words):
        if i > 0 and w in ACRONYMS:
            out.append(ACRONYMS[w])
        elif w in ACRONYMS and w.isupper():
            out.append(ACRONYMS[w])
        else:
            out.append(w)
    return ' '.join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('title_lua')
    ap.add_argument('-o', '--out', default='internal/xidb/titles_gen.go')
    args = ap.parse_args()

    titles = {}
    with open(args.title_lua, encoding='utf-8') as fh:
        for line in fh:
            m = ENTRY.match(line)
            if m:
                titles[int(m[2])] = humanize(m[1])

    if not titles:
        sys.exit(f'no title entries found in {args.title_lua}')

    os.makedirs(os.path.dirname(args.out) or '.', exist_ok=True)
    src = os.path.basename(args.title_lua)
    with open(args.out, 'w', encoding='utf-8') as fh:
        fh.write('// Code generated by tools/gen_titles.py from '
                 f'scripts/enum/{src}. DO NOT EDIT.\n\n')
        fh.write('package xidb\n\nimport "fmt"\n\n')
        fh.write('// titleNames maps a char_stats.title id to its display name.\n')
        fh.write('var titleNames = map[int]string{\n')
        for tid in sorted(titles):
            name = titles[tid].replace('\\', '\\\\').replace('"', '\\"')
            fh.write(f'\t{tid}: "{name}",\n')
        fh.write('}\n\n')
        fh.write('// TitleName returns the display name for a title id. Id 0 means\n')
        fh.write('// the character has no title equipped.\n')
        fh.write('func TitleName(id int) string {\n')
        fh.write('\tif id == 0 {\n\t\treturn ""\n\t}\n')
        fh.write('\tif n, ok := titleNames[id]; ok {\n\t\treturn n\n\t}\n')
        fh.write('\treturn fmt.Sprintf("Title #%d", id)\n')
        fh.write('}\n')

    print(f'{len(titles)} titles -> {args.out}')


if __name__ == '__main__':
    main()
