#!/usr/bin/env python3
"""Generate internal/xidb/missions_gen.go from the server's mission tables.

chars.missions is a blob of 15 missionlog_t structs (see mmo.h), each carrying
the currently accepted mission id for one log plus a completion array. Turning
those ids into names needs scripts/globals/missions.lua, which is the only
authoritative id-to-name mapping and changes whenever the server adds content.

    ./tools/gen_missions.py ../xiserver/scripts/globals/missions.lua
"""

import argparse
import os
import re
import sys

# Block headers look like either of these:
#   [xi.mission.area[xi.mission.log_id.SANDORIA]] =
#   ['nation'] =
BLOCK_ENUM = re.compile(r"^\s*\[xi\.mission\.area\[xi\.mission\.log_id\.(\w+)\]\]\s*=")
BLOCK_PLAIN = re.compile(r"^\s*\['(\w+)'\]\s*=")
ENTRY = re.compile(r"^\s*([A-Z0-9_]+)\s*=\s*(\d+)\s*,")
LOG_ID = re.compile(r"^\s*(\w+)\s*=\s*(\d+)\s*,")

# Display names for the logs. The Lua only carries slugs like 'toau', which is
# not what a reader wants to see on a character page.
LOG_LABELS = {
    "SANDORIA": "San d'Oria",
    "BASTOK": "Bastok",
    "WINDURST": "Windurst",
    "ZILART": "Rise of the Zilart",
    "COP": "Chains of Promathia",
    "TOAU": "Treasures of Aht Urhgan",
    "WOTG": "Wings of the Goddess",
    "ACP": "A Crystalline Prophecy",
    "AMK": "A Moogle Kupo d'Etat",
    "ASA": "A Shantotto Ascension",
    "SOA": "Seekers of Adoulin",
    "ROV": "Rhapsodies of Vana'diel",
    "TVR": "The Voracious Resurgence",
    "ASSAULT": "Assault",
    "CAMPAIGN": "Campaign",
}

# Short forms, for the compact label the character page shows.
LOG_SHORT = {
    "SANDORIA": "San d'Oria",
    "BASTOK": "Bastok",
    "WINDURST": "Windurst",
    "ZILART": "RoZ",
    "COP": "CoP",
    "TOAU": "ToAU",
    "WOTG": "WotG",
    "ACP": "ACP",
    "AMK": "AMK",
    "ASA": "ASA",
    "SOA": "SoA",
    "ROV": "RoV",
    "TVR": "TVR",
    "ASSAULT": "Assault",
    "CAMPAIGN": "Campaign",
}

SMALL = {"of", "the", "to", "a", "in", "and", "for", "at", "on"}


def humanize(ident):
    words = ident.split("_")
    out = []
    for i, w in enumerate(words):
        low = w.lower()
        out.append(low if i > 0 and low in SMALL else low.capitalize())
    return " ".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("missions_lua")
    ap.add_argument("-o", "--out", default="internal/xidb/missions_gen.go")
    args = ap.parse_args()

    lines = open(args.missions_lua, encoding="utf-8").read().split("\n")

    # Pass one: the log id enum.
    log_ids = {}
    in_enum = False
    for line in lines:
        if "xi.mission.log_id =" in line:
            in_enum = True
            continue
        if in_enum:
            if line.strip() == "}":
                break
            m = LOG_ID.match(line)
            if m:
                log_ids[m[1]] = int(m[2])

    # Pass two: mission ids per block, only inside xi.mission.id.
    blocks = {}
    current = None
    started = False
    for line in lines:
        if "xi.mission.id =" in line:
            started = True
            continue
        if not started:
            continue
        m = BLOCK_ENUM.match(line) or BLOCK_PLAIN.match(line)
        if m:
            current = m[1]
            blocks.setdefault(current, {})
            continue
        if current:
            e = ENTRY.match(line)
            if e:
                mid = int(e[2])
                # 65535 is the NONE sentinel, not a mission.
                if mid < 65535:
                    blocks[current].setdefault(mid, humanize(e[1]))

    if not log_ids or not blocks:
        sys.exit("failed to parse the mission tables")

    known = [(name, lid) for name, lid in sorted(log_ids.items(), key=lambda kv: kv[1])]

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("// Code generated by tools/gen_missions.py from "
                 "scripts/globals/missions.lua. DO NOT EDIT.\n\n")
        fh.write("package xidb\n\n")

        fh.write("// MissionLogs are the mission logs in chars.missions order.\n")
        fh.write("// The blob holds one missionlog_t per entry, indexed by LogID.\n")
        fh.write("var MissionLogs = []MissionLogDef{\n")
        for name, lid in known:
            label = LOG_LABELS.get(name, humanize(name))
            short = LOG_SHORT.get(name, name)
            fh.write(f'\t{{LogID: {lid}, Slug: "{name.lower()}", '
                     f'Short: "{short}", Label: "{label}"}},\n')
        fh.write("}\n\n")

        fh.write("// missionNames maps a log id to that log's mission id to name.\n")
        fh.write("var missionNames = map[int]map[int]string{\n")
        for name, lid in known:
            entries = blocks.get(name.lower()) or blocks.get(name)
            if not entries:
                fh.write(f"\t{lid}: {{}}, // {name}: no mission table in the Lua\n")
                continue
            fh.write(f"\t{lid}: {{ // {name}\n")
            for mid in sorted(entries):
                text = entries[mid].replace("\\", "\\\\").replace('"', '\\"')
                fh.write(f'\t\t{mid}: "{text}",\n')
            fh.write("\t},\n")
        fh.write("}\n")

    total = sum(len(v) for v in blocks.values())
    print(f"{len(known)} logs, {total} mission names -> {args.out}")
    for name, lid in known:
        n = len(blocks.get(name.lower()) or blocks.get(name) or {})
        print(f"  {lid:2d} {name:<10s} {n:4d} missions")


if __name__ == "__main__":
    main()
